# 1. The Database Name
# If you ran "CREATE DATABASE exercise_db;", change the end of this URL:
spring.datasource.url=jdbc:postgresql://localhost:5432/exercise_db
spring.jpa.hibernate.ddl-auto=create
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# 2. The Username
# On macOS Homebrew, the default superuser is usually your Mac username.
# Try "aliakbar". If that fails, use "postgres".
spring.datasource.username=aliakbar

# 3. The Password
# By default, Homebrew PostgreSQL does not have a password.
# Leave this completely blank.
spring.datasource.password=